src/Entity/Pin.php
<?php

namespace App\Entity;

use App\Repository\PinRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=PinRepository::class)
 * @ORM\Table(name="pins")
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
class Pin
{

    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le titre ne peut être vide")
     * @Assert\Length(min=3,minMessage="La longueur du titre doit être supérieure à 3 caractère")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Assert\Length(min=10)
     */
    private $description;

    // , size="imageSize" permettrait de sauvegarder la taille de l'image
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="pin_image", fileNameProperty="imageName")
     * @Assert\Image(maxSize="8M")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;
use Liip\ImagineBundle\Config\Filter\Argument\Size;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{

    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please insert your first name")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please insert your lastt name")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Please insert your email")
     * @Assert\Email()message="Please insert a valid email")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private $pins;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->pins = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Pin[]
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }

    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->removeElement($pin)) {
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    public function getGravatarUrl(?int $size = 100): ?string
    {
        //return "https://www.gravatar.com/avatar/" . md5(strtolower(trim($this->getEmail()))) . "/?s=" . $size;
        return sprintf("https://www.gravatar.com/avatar/%s/?s=%d", md5(strtolower(trim($this->getEmail()))), $size);
    }
    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Pin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        /*
        $imageFileConstraints = [];

        $isEdit = $options['method']=='PUT';

        if ($isEdit)*/
        $builder
        ->add('imageFile', VichImageType::class, [
            'label' => 'Image (Png or Jpg)',
            'required' => false,
            'allow_delete' => true,
            //'delete_label' => '...',
            //'download_label' => '...',
            'download_uri' => false,
            //'image_uri' => true,
            'imagine_pattern' => 'squared_thumbnail_small',
            //'asset_helper' => true,
            //'constraints' => [
//                new Image(['maxSize' =>'1M'])
            //]
        ])
        ->add('title',TextType::class,['label'=>'Titre', 'attr' => ['autofocus' => true]])
        ->add('description',TextareaType::class, ['label'=>'Desc', 'attr' => ['cols' => '60', 'rows'=>'10']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pin::class,
        ]);
    }
}

src/Controller/PinsController.php
<?php

namespace App\Controller;

use App\Entity\Pin;
use App\Form\PinType;
use App\Repository\PinRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
// use Symfony\Component\Routing\Annotation\Route;

class PinsController extends AbstractController
{


    /* @Route("/pins", name="pins")
    /**
     * @Route("/")
     */
    public function index(PinRepository $repo): Response
    {

        $pins = $repo->findBy([], ['createdAt' => 'DESC']);

        return $this->render('pins/index.html.twig', [
            'controller_name' => 'PinsController',
            'pins' => $pins,
        ]);
        /*return $this->json([
            'message' => 'Welcome to your new controller',
            'path' => 'src/Controller/PinsController.php',
            ]);*/
        //return new Response('Hello World');
    }

    /**
     * @ParamConverter("pin")
     */
    public function show(Pin $pin /*PinRepository $repo,int $id*/): Response
    {
        //     $pin=$repo->find($id);
        //     if ( ! $pin)
        //     {
        // throw $this->createNotFoundException("Pin #". $id ." not found");
        //     }
        return $this->render('pins/show.html.twig', [
            'controller_name' => 'PinsController',
            'pin' => $pin,
        ]);
    }

    /**
     * @ParamConverter("pin")
     * IsGranted ("PIN_MANAGE", subject="pin")
     */
    public function delete(Request $request, EntityManagerInterface $em, Pin $pin): Response
    {
        if ($this->isCsrfTokenValid('pin_deletion_' . $pin->getId(), $request->request->get('csrf_token'))) {
            $em->remove($pin);
            $em->flush();
            //permet d'afficher un message 
            $this->addFlash('info', 'Pin successfully deleted!');
        }
        return $this->redirectToRoute('app_home');
    }
    /**
     * @ParamConverter("pin")
     * @Security("is_granted('PIN_MANAGE', pin)")
     
     */
    public function edit(Request $request, EntityManagerInterface $em, Pin $pin): Response
    {

        // $this->denyAccessUnlessGranted('PIN_EDIT', $pin);
        $form = $this->createForm(PinType::class, $pin, [
            'method' => 'PUT',
        ]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();
            //permet d'afficher un message 
            $this->addFlash('success', 'Pin successfully updated!');
            return $this->redirectToRoute('app_pins_show', ['id' => $pin->getId()]);
        }
        return $this->render('pins/edit.html.twig', [
            'controller_name' => 'PinsController',
            'pin' => $pin,
            'monForm' => $form->createView(),
        ]);
    }


    /**
     * @Route("/pin/create", name="app_pins_create" ,methods="GET|POST")
     * @Security("is_granted('PIN_CREATE')")
     */
    public function create(Request $request, EntityManagerInterface $em, UserRepository $userRepo): Response
    {

        // if (!$this->getUser()) {
        //     throw $this->createAccessDeniedException('Tentative de création sans être connecté');
        //     //$this->addFlash('error', 'Not Connected!');
        //     //return $this->redirectToRoute('app_login');
        // }
        // if (!$this->getUser()->isVerified) {
        //     throw $this->createAccessDeniedException('You need to have a verified account');
        //     //$this->addFlash('error', 'Not Connected!');
        //     //return $this->redirectToRoute('app_login');
        // }

        $pin = new Pin;

        $form = $this->createForm(PinType::class, $pin);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pin->setUser($this->getUser());
            $em->persist($pin);
            $em->flush();
            //permet d'afficher un message 
            $this->addFlash('success', 'Pin successfully created!');
            return $this->redirectToRoute('app_pins_show', ['id' => $pin->getId()]);
        }
        return $this->render('pins/create.html.twig', [
            'controller_name' => 'PinsController',
            'monForm' => $form->createView(),
        ]);
    }
}

templates/pins/_form.html.twig
{{ form_start(monForm) }}
    {{ form_widget(monForm) }}
    <input type="Submit" value ="{{ submitButtonText|default('Create a Pin') }}" class="btn btn-primary btn-block" formnovalidate>
{{ form_end(monForm) }}

templates/pins/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Pin!{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-6 mx-auto">
        <h1>Create a new pin</h1>
        {{ include ('pins/_form.html.twig', {'submitButtonText': 'Create Pin'}) }}
    </div>
</div>
{% endblock %}

templates/pins/edit.html.twig
{% extends 'base.html.twig' %}

{% block title 'Edit Pin #' ~ pin.id  %}

{% block body %}

<div class="row">
    <div class="col-md-6 mx-auto">
        <h1>Edit Pin # {{ pin.id }}</h1>
        {{ include ('pins/_form.html.twig', {'submitButtonText': 'Update Pin'}) }}
    </div>
</div>
{% endblock %}

templates/pins/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PinsController!
{% endblock %}

{% block body %}
	<!-- <style>
									    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
									    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
									</style>-->
	{% set pin_count = pins|length %}
	<div class="example-wrapper">

		{% if (pin_count >0) %}
			<h1 class="mb-4 text-center text-muted">
				{{ pluralize (pin_count, 'Pin') }}
				All Pins! ✅</h1>

			<p class="mb-5">Il y a
				{{ pluralize (pin_count, 'Pin') }}
				dans la base |
				<a href="{{ path('app_pins_create') }}">
					Create a pin
				</a>
			</p>


			{% for  row in pins|batch(3) %}
				<div class="row mb-5">
					{% for  pin in row %}
						<div class="col-md-4">
							<article class="pin bg-white rounded shadow">
								<div class="mw-100 overflow-hidden rounded-top">
									<a href="{{ path('app_pins_show', { 'id' : pin.id } ) }}">
										<img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/images/placeholder.jpg')) | imagine_filter('squared_thumbnail_medium')}}" alt="{{ pin.title }}" class="w-100 "/>
									</a>
								</div>
								<h2 class="h5 pl-3 pt-3">
									<a class="text-secondary text-decoration-none" href="{{ path('app_pins_show', { 'id' : pin.id } ) }}">
										{{ pin.title }}
									</a>
								</h2>
								<p class="pl-3 pb-3 text-muted">
									<small>
										Submitted by
										{{ pin.user.fullName }}
										{{ pin.createdAt|ago  }}</small>
								</p>
								<!--date("d/M/Y")-->
								{# <a href="#" onclick="event.preventDefault(); confirm ('Are you sure??') && document.getElementById('js-pin-delete-form-{{ pin.id }}').submit()" class="m-3 btn btn-warning">&times; Delete?</a>
																<form id="js-pin-delete-form-{{ pin.id }}" action="{{ path('app_pins_delete', { 'id' : pin.id } ) }}" method="post" style="display:none">
																	<input type="hidden" name="csrf_token" value="{{ csrf_token('pin_deletion_' ~ pin.id ) }}">
																	<input type="hidden" name="_method" value="DELETE">
																</form> #}
							</article>
						</div>
					{% else %}
						<p>
							Sorry, no pin yet!
							<a href="{{ path('app_pins_create') }}">Be The first
							</a>
						</p>
					{% endfor %}

				</div>
			{% endfor %}
		{% else %}
			<p class="mt-5 h1 text-center ">
				Sorry, no pin yet!
				<a href="{{ path('app_pins_create') }}">Be The first
				</a>
			</p>
		{% endif %}
	{% endblock %}

templates/pins/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ pin.title }}!
{% endblock %}

{% block body %}

	<div class="row">
		<div class="col-md-6 mx-auto">
			<article class="pin bg-white rounded shadow">
				<div class="mw-100 overflow-hidden rounded-top">
					<img src="{{ (pin.imageName ? vich_uploader_asset(pin) : asset('build/images/placeholder.jpg')) | imagine_filter('squared_thumbnail_medium')}}" alt="{{ pin.title }}" class="w-100 "/>
				</div>
				<div class="p-3">
					<h1 class="h5 text-secondary">
						{{ pin.title }}
					</h1>
					<p class="text-muted">
						<small>
							<time datetime="{{ pin.createdAt|date("d/M/Y H:i:s") }}">Submitted
								{{ pin.createdAt|ago  }}
							</time>
							by  [{{ pin.user.fullName }}
							] -
							<a href="{{ vich_uploader_asset(pin) }}">
								Télécharger?</a>
						</small>
					</p>
					<!--date("d/M/Y")-->
					<p class="pt-3 text-break">{{ pin.description }}</p>
					{% if (is_granted('PIN_MANAGE',pin)) %}
						<div class="pt-3">
							<p>
								<a href="{{ path('app_pins_edit', { 'id' : pin.id } ) }}" class="btn btn-light">
									Edit</a>
								<a href="#" onclick="event.preventDefault(); confirm ('Are you sure??') && document.getElementById('js-pin-delete-form').submit()" class="btn btn-light">
									Delete</a>
							</p>
							<form id="js-pin-delete-form" action="{{ path('app_pins_delete', { 'id' : pin.id } ) }}" method="post" style="display:none">
								<input type="hidden" name="csrf_token" value="{{ csrf_token('pin_deletion_' ~ pin.id ) }}">
								<input type="hidden" name="_method" value="DELETE">
							</form>
						</div>
					{% endif %}
				</div>
			</article>


		</div>
	</div>


{% endblock %}